fix: don't show exception to user
There is already a nice explanation on why the detection failed,
so no need to show an exception dialog about failing to start it.

	Uncaught Exception:
	Error: spawn podman ENOENT

Signed-off-by: Anders F Björklund <anders.f.bjorklund@gmail.com>